// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Joel Winarske
//
// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_proto.py. Regenerate with:  tool/gen_proto.py

/// Camera control: naming, control-status arbitration, capabilities.
///
/// Its own library so that an application importing it does not also
/// ship the descriptors of every other feature: the .pbjson.dart tables
/// are reflective data and do not tree shake.
library gopro_native.proto.control;

export '../src/generated/proto/camera_control.pb.dart';
export '../src/generated/proto/camera_control.pbenum.dart';
export '../src/generated/proto/request_get_camera_capabilities.pb.dart';
export '../src/generated/proto/request_get_camera_capabilities.pbenum.dart';
export '../src/generated/proto/response_generic.pb.dart';
export '../src/generated/proto/response_generic.pbenum.dart';
export '../src/generated/proto/set_camera_control_status.pb.dart';
export '../src/generated/proto/set_camera_control_status.pbenum.dart';
