// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Joel Winarske
//
// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_proto.py. Regenerate with:  tool/gen_proto.py

/// Livestreaming setup and status.
///
/// Its own library so that an application importing it does not also
/// ship the descriptors of every other feature: the .pbjson.dart tables
/// are reflective data and do not tree shake.
library gopro_native.proto.livestream;

export '../src/generated/proto/live_streaming.pb.dart';
export '../src/generated/proto/live_streaming.pbenum.dart';
export '../src/generated/proto/response_generic.pb.dart';
export '../src/generated/proto/response_generic.pbenum.dart';
