// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Joel Winarske
//
// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_proto.py. Regenerate with:  tool/gen_proto.py

/// Media: high-resolution transfer and turbo mode.
///
/// Its own library so that an application importing it does not also
/// ship the descriptors of every other feature: the .pbjson.dart tables
/// are reflective data and do not tree shake.
library gopro_native.proto.media;

export '../src/generated/proto/media.pb.dart';
export '../src/generated/proto/media.pbenum.dart';
export '../src/generated/proto/response_generic.pb.dart';
export '../src/generated/proto/response_generic.pbenum.dart';
export '../src/generated/proto/turbo_transfer.pb.dart';
export '../src/generated/proto/turbo_transfer.pbenum.dart';
