// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Joel Winarske
//
// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_proto.py. Regenerate with:  tool/gen_proto.py

/// Presets and preset groups.
///
/// Its own library so that an application importing it does not also
/// ship the descriptors of every other feature: the .pbjson.dart tables
/// are reflective data and do not tree shake.
library gopro_native.proto.presets;

export '../src/generated/proto/preset_status.pb.dart';
export '../src/generated/proto/preset_status.pbenum.dart';
export '../src/generated/proto/request_get_preset_status.pb.dart';
export '../src/generated/proto/request_get_preset_status.pbenum.dart';
export '../src/generated/proto/response_generic.pb.dart';
export '../src/generated/proto/response_generic.pbenum.dart';
