#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Joel Winarske
"""Generate the Open GoPro protobuf layer.

COHN, livestreaming, network management, preset status and camera control all
speak protobuf, so several features depend on this. The 11 .proto sources are
vendored under tool/upstream/proto/ for the same reason the constants are: so
generation is reproducible without a checkout of the SDK, and the provenance
of the generated code is auditable.

The generated files carry an SPDX header that this script adds. Headers put
there by hand would be erased on the next run, which is a mistake the
constants generator already made once.

Output is split into per-feature libraries under lib/proto/. The .pbjson.dart
descriptors are reflective data and resist tree shaking, so an application
using only capture control should not have to ship the livestream and
network-management descriptors. Every .proto must be assigned to a feature
group below; one that is not is an error rather than a file that quietly
never gets exported.

Requires protoc and protoc-gen-dart (dart pub global activate protoc_plugin).

Usage:
    tool/gen_proto.py
    tool/gen_proto.py --check     # verify the generated files are current
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile

GOPRO_COPYRIGHT = "Copyright © 2021-2024 GoPro, Inc."

# Which .proto belongs to which feature library. Shared by everything, so it
# is re-exported from each group rather than forcing callers to import two.
COMMON = "response_generic"

GROUPS: dict[str, tuple[str, list[str]]] = {
    "control": (
        "Camera control: naming, control-status arbitration, capabilities.",
        [
            "camera_control",
            "set_camera_control_status",
            "request_get_camera_capabilities",
        ],
    ),
    "cohn": ("Camera On the Home Network: provisioning and status.", ["cohn"]),
    "livestream": ("Livestreaming setup and status.", ["live_streaming"]),
    "media": (
        "Media: high-resolution transfer and turbo mode.",
        ["media", "turbo_transfer"],
    ),
    "network": (
        "Network management: access points, scanning, connection.",
        ["network_management"],
    ),
    "presets": (
        "Presets and preset groups.",
        ["preset_status", "request_get_preset_status"],
    ),
}

# The three files protoc emits per .proto.
SUFFIXES = (".pb.dart", ".pbenum.dart", ".pbjson.dart")


class GenError(Exception):
    pass


def header(source: str) -> str:
    return f"""// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Joel Winarske
//
// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_proto.py from tool/upstream/proto/{source}.
// Regenerate with:  tool/gen_proto.py
//
// Derived from the Open GoPro protobuf definitions, which are MIT licensed:
//   {GOPRO_COPYRIGHT}
// The full notice is in tool/upstream/LICENSE.gopro and must ship with any
// distribution of this package.
"""


def library(name: str, description: str, protos: list[str]) -> str:
    exports = sorted({*protos, COMMON})
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Joel Winarske",
        "//",
        "// GENERATED FILE — DO NOT EDIT.",
        "//",
        "// Generated by tool/gen_proto.py. Regenerate with:  tool/gen_proto.py",
        "",
        f"/// {description}",
        "///",
        "/// Its own library so that an application importing it does not also",
        "/// ship the descriptors of every other feature: the .pbjson.dart tables",
        "/// are reflective data and do not tree shake.",
        f"library gopro_native.proto.{name};",
        "",
    ]
    for p in exports:
        lines.append(f"export '../src/generated/proto/{p}.pb.dart';")
        lines.append(f"export '../src/generated/proto/{p}.pbenum.dart';")
    lines.append("")
    return "\n".join(lines)


def dart_format(paths: list[pathlib.Path]) -> None:
    """Formats in place.

    CI runs `dart format --set-exit-if-changed lib/`, so output that the
    formatter would rewrite makes --check report drift forever: the generator
    and the formatter disagree about the same content and neither yields.
    """
    dart = shutil.which("dart")
    if dart is None:
        raise GenError(
            "dart not found on PATH. The generated sources are formatted, so "
            "without it this would emit output that CI immediately rejects."
        )
    r = subprocess.run(
        [dart, "format", *[str(p) for p in paths]],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        raise GenError(f"dart format failed: {r.stderr.strip()}")


def generate(upstream: pathlib.Path, tmp: pathlib.Path) -> None:
    protoc = shutil.which("protoc")
    if protoc is None:
        raise GenError("protoc not found on PATH")
    if shutil.which("protoc-gen-dart") is None:
        raise GenError(
            "protoc-gen-dart not found on PATH. Install it with:\n"
            "  dart pub global activate protoc_plugin\n"
            "and put ~/.pub-cache/bin on PATH."
        )

    sources = sorted(upstream.glob("*.proto"))
    if not sources:
        raise GenError(f"no .proto files in {upstream}")

    r = subprocess.run(
        [protoc, f"--dart_out={tmp}", f"--proto_path={upstream}",
         *[str(s) for s in sources]],
        capture_output=True, text=True,
    )
    # protoc reports an unused import in preset_status.proto. That is
    # upstream's to fix; surface it rather than swallowing it, so a genuine
    # warning introduced later is not lost in a silent stream.
    if r.stderr.strip():
        for line in r.stderr.strip().splitlines():
            print(f"  protoc: {line}")
    if r.returncode != 0:
        raise GenError("protoc failed")


def build(upstream: pathlib.Path, tmp: pathlib.Path) -> dict[pathlib.Path, str]:
    """Returns the full generated tree as {relative path: content}."""
    generate(upstream, tmp)

    stems = sorted(p.stem for p in upstream.glob("*.proto"))
    assigned = {p for _, protos in GROUPS.values() for p in protos} | {COMMON}
    if orphans := set(stems) - assigned:
        raise GenError(
            f"not assigned to a feature group: {sorted(orphans)}. "
            "Add them to GROUPS, or they are generated but never exported."
        )
    if missing := assigned - set(stems):
        raise GenError(f"assigned to a group but not vendored: {sorted(missing)}")

    # Prepend the SPDX header to every protoc output, then format the lot.
    produced = []
    for stem in stems:
        for suffix in SUFFIXES:
            f = tmp / f"{stem}{suffix}"
            if not f.exists():
                raise GenError(f"protoc did not emit {f.name}")
            f.write_text(header(f"{stem}.proto") + "\n" + f.read_text())
            produced.append(f)

    libs = tmp / "_libs"
    libs.mkdir()
    for name, (description, protos) in GROUPS.items():
        f = libs / f"{name}.dart"
        f.write_text(library(name, description, protos))
        produced.append(f)

    dart_format(produced)

    out: dict[pathlib.Path, str] = {}
    for stem in stems:
        for suffix in SUFFIXES:
            name = f"{stem}{suffix}"
            out[pathlib.Path("lib/src/generated/proto") / name] = (
                tmp / name
            ).read_text()
    for name in GROUPS:
        out[pathlib.Path("lib/proto") / f"{name}.dart"] = (
            libs / f"{name}.dart"
        ).read_text()
    return out


def main() -> int:
    root = pathlib.Path(__file__).parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--upstream", type=pathlib.Path,
                    default=root / "tool" / "upstream" / "proto")
    ap.add_argument("--root", type=pathlib.Path, default=root)
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files are up to date")
    args = ap.parse_args()

    try:
        with tempfile.TemporaryDirectory() as tmp:
            tree = build(args.upstream, pathlib.Path(tmp))
    except GenError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.check:
        stale = []
        for rel, content in sorted(tree.items()):
            target = args.root / rel
            if not target.exists() or target.read_text() != content:
                stale.append(str(rel))
        # A file left behind after its .proto is removed upstream still
        # compiles and still ships, so absence has to be checked too.
        for d, keep in (
            ("lib/src/generated/proto", {p.name for p in tree
                                         if p.parent.name == "proto"}),
            ("lib/proto", {f"{n}.dart" for n in GROUPS}),
        ):
            existing = args.root / d
            if existing.is_dir():
                for f in existing.glob("*.dart"):
                    if f.name not in keep:
                        stale.append(f"{d}/{f.name} (no longer generated)")
        if stale:
            print("stale generated files:", file=sys.stderr)
            for s in sorted(stale):
                print(f"  {s}", file=sys.stderr)
            print("run tool/gen_proto.py", file=sys.stderr)
            return 1
        print(f"generated protobuf files up to date ({len(tree)} files)")
        return 0

    for d in ("lib/src/generated/proto", "lib/proto"):
        target = args.root / d
        if target.is_dir():
            shutil.rmtree(target)
        target.mkdir(parents=True)
    for rel, content in tree.items():
        (args.root / rel).write_text(content)

    protos = len(list(args.upstream.glob("*.proto")))
    print(f"{protos} protos -> {len(tree)} files "
          f"({len(GROUPS)} feature libraries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
